spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

file:
  server:
    url: http://localhost:9000/