server:
  port: 8088

spring:
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: hfyj-safe
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

logging:
  level:
    com.fhyj.safe.mapper : debug

jasypt:
  encryptor:
    password: fhyj@2023
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

fhyj:
  user:
    username: qinchao
    password: ENC(66C4uybMCVnyXgBx/eG9iQ==)
