spring:
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: ENC(fpx0ycp6MtWJlQemcoLsnZYk08ooR2p/)
  datasource:
    url: jdbc:mysql://localhost:3306/fhyj?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
elk:
  logstash:
    url: localhost:9061
