spring:
  elasticsearch:
    uris: http://10.9.1.130:9200
  datasource:
    url: jdbc:mysql://localhost:3306/fhyj?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

elk:
  logstash:
    url: 10.9.1.130:5044

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
